name: unlockGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cloudpickle
  - coverage
  - numpy=1.19.*
  - pandas
  - pip
  - pydocstyle
  - pytest
  - pytest-cov
  - python=3.8
  - virtualenv
  - pip:
      - build
      - bumpversion
      - coveralls
      - insegel
      - pyarrow
      - pymatgen==2021.2.8
      - megnet
      - requests
      - sphinx
      - tensorflow
      - tensorflow-probability
      - tox
      - twine
