name: unlockNN
channels:
  - defaults
dependencies:
  - numpy=1.19.*
  - pip
  - python=3.8
  - pip:
      - pyarrow
      - pymatgen==2021.2.8
      - megnet
      - requests
      - tensorflow
      - tensorflow-probability
